#!/bin/bash
NAME=${1:-"bdd-proiect"}
ORACLE_PWD=${2:-"password"}

echo "Removing tables from container $NAME..."
docker exec -i $NAME sqlplus -S system/$ORACLE_PWD@//localhost:1521/XEPDB1 <<EOF
DROP TABLE USER_STATS CASCADE CONSTRAINTS;
DROP TABLE GAMES_HISTORY CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE GAMES CASCADE CONSTRAINTS;
DROP TABLE WRITING_SYSTEMS CASCADE CONSTRAINTS;
DROP TABLE CONTINENTS CASCADE CONSTRAINTS;
EXIT;
EOF
